image: datazucar/ubuntu:16.04

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

.before_script:
  # Install composer dependencies
  - composer install

# Run PHP Code Sniffer.
.code_sniffer:
  script:
  - vendor/bin/phpcs --standard=vendor/yiisoft/yii2-coding-standards/Yii2/ --extensions=php --ignore=vendor/ .
# Prueba de docker.
test:
  script:
  - echo 'Hola Mundo'
  