# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/

# Run PHP Code Sniffer.
code_sniffer:7.0:
  image: git.versat.azcuba.cu:4567/docker/php:7.0
  before_script:
  - bash /opt/composer/install.sh
  - composer install
  script:
  - vendor/bin/phpcs --standard=vendor/yiisoft/yii2-coding-standards/Yii2/ --extensions=php --ignore=vendor/ .

# Prueba de docker.
.test:trusty:
  image: git.versat.azcuba.cu:4567/docker/ubuntu:trusty
  script:
  - echo 'Probando Ubuntu:trusty'
  - lsb_release -a
  - echo 'Mostrando sources.list'
  - cat /etc/apt/sources.list
.test:xenial:
  image: git.versat.azcuba.cu:4567/docker/ubuntu:xenial
  script:
  - echo 'Listando directorio'
  - ls -l
  - echo 'Probando Ubuntu:xenial'
#  - lsb_release -a
  - echo 'Mostrando sources.list'
  - cat /etc/apt/sources.list
  